version: '3.4'

services:
  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: PA$$
      MYSQL_ROOT_HOST: "%"
    ports:
      - "5199:3306"

  identity-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - Jwt__Issuer=http://identity-api
      - Jwt__Audience=http://identity-api
      - Kestrel__Endpoints__HTTP__Url=http://0.0.0.0:80
      - ConnectionStrings__IdentityDb=Server=mysql;Database=hrm.identity;User Id=root;Password=PA$$
    ports:
      - "5101:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro

  employee-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - Jwt__Issuer=http://identity-api
      - Jwt__Audience=http://identity-api
      - Kestrel__Endpoints__HTTP__Url=http://0.0.0.0:80
      - Kestrel__Endpoints__gRPC__Url=http://0.0.0.0:81
      - ConnectionStrings__EmployeeDb=Server=mysql;Database=hrm.employee;User Id=root;Password=PA$$
    ports:
      - "5102:80"
      - "6102:81"

  web-apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - Jwt__Issuer=http://identity-api
      - Jwt__Audience=http://identity-api
      - ReverseProxy__Clusters__identity__Destinations__default__Address=http://identity-api
      - ReverseProxy__Clusters__employee__Destinations__default__Address=http://employee-api
      - urls__Identity=http://identity-api
      - urls__Employee=http://employee-api
      - urls__GrpcIdentity=http://identity-api:81
      - urls__GrpcEmployee=http://employee-api:81
    ports:
      - "5100:80"

