version: '3.4'

services:
  mysql:
    image: mysql:latest
    restart: always

  identity-api:
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: .
      dockerfile: src/Services/Identity/Identity.API/Dockerfile
    depends_on:
      - mysql

  employee-api:
    image: ${DOCKER_REGISTRY-}employeeapi
    build:
      context: .
      dockerfile: src/Services/EmployeeManagement/EmployeeManagement.API/Dockerfile
    depends_on:
      - mysql

  web-apigateway:
    image: ${DOCKER_REGISTRY-}webapigateway
    build:
      context: .
      dockerfile: src/ApiGateways/Web.ApiGateway/Dockerfile
    depends_on:
      - mysql
      - identity-api
      - employee-api