version: '3.4'

services:
    mysql:
        environment:
            MYSQL_ROOT_PASSWORD: PA$$
            MYSQL_ROOT_HOST: "%"
        ports:
            - "5199:3306"

    identity-api:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_HTTP_PORTS=8080
            - Logging__Loglevel__Default=Debug
            - Logging__Loglevel__Microsoft.AspNetCore=Debug 
            - Jwt__Issuer=http://identity-api
            - Jwt__Audience=http://identity-api
            - Kestrel__Endpoints__HTTP__Url=http://0.0.0.0:80
            - ConnectionStrings__IdentityDb=Server=mysql;Database=hrm.identity;User Id=root;Password=PA$$
            - PATH_BASE=/identity-api
        ports:
            - "5101:80"
        volumes:
            - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro

    employee-api:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_HTTP_PORTS=8080
            - Logging__Loglevel__Default=Debug
            - Logging__Loglevel__Microsoft.AspNetCore=Debug 
            - Jwt__Issuer=http://identity-api
            - Jwt__Audience=http://identity-api
            - Kestrel__Endpoints__HTTP__Url=http://0.0.0.0:80
            - Kestrel__Endpoints__gRPC__Url=http://0.0.0.0:81
            - ConnectionStrings__EmployeeDb=Server=mysql;Database=hrm.employee;User Id=root;Password=PA$$
            - PATH_BASE=/employee-api
        ports:
            - "5102:80"
            - "6102:81"

    web-apigateway:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_HTTP_PORTS=8080
            - Logging__Loglevel__Default=Debug
            - Logging__Loglevel__Microsoft.AspNetCore=Debug 
            - Jwt__Issuer=http://identity-api
            - Jwt__Audience=http://identity-api
            - Kestrel__Endpoints__HTTP__Url=http://0.0.0.0:80
            - Reverseproxy__Clusters__identity__Destinations__default__Address=http://identity-api
            - Reverseproxy__Clusters__employee__Destinations__default__Address=http://employee-api
            - Urls__Identity=http://identity-api
            - Urls__Employee=http://employee-api
            - Urls__GrpcIdentity=http://identity-api:81
            - Urls__GrpcEmployee=http://employee-api:81
        ports:
            - "5100:80"
  
    fluent-bit:
        environment:
            - FLB_ES_HOST=elasticsearch
            - FLB_ES_PORT=9200
        ports:
            - 24224:24224
        volumes:
            - ./fluent-bit:/fluent-bit/etc

    elasticsearch:
        mem_limit: 2g
        environment:
            - discovery.type=single-node
        ports:
            - 9200:9200
            - 9300:9300
        volumes:
            - /var/lib/elasticsearch

    kibana:
        environment:
            - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
        ports:
            - 5601:5601
    
    # grafana:
    #     ports:
    #         - 3000:3000
    #     volumes:
    #     - /var/lib/grafana